//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisjuri.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModel : DbContext
    {
        public DataModel()
            : base("name=DataModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<curso> curso { get; set; }
        public virtual DbSet<documento> documento { get; set; }
        public virtual DbSet<faculdade> faculdade { get; set; }
        public virtual DbSet<foto> foto { get; set; }
        public virtual DbSet<funcao> funcao { get; set; }
        public virtual DbSet<inscricao> inscricao { get; set; }
        public virtual DbSet<juri> juri { get; set; }
        public virtual DbSet<npj> npj { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<presenca> presenca { get; set; }
        public virtual DbSet<processo> processo { get; set; }
        public virtual DbSet<ques_absolvicao> ques_absolvicao { get; set; }
        public virtual DbSet<ques_agravante> ques_agravante { get; set; }
        public virtual DbSet<ques_atenuante> ques_atenuante { get; set; }
        public virtual DbSet<ques_autoria> ques_autoria { get; set; }
        public virtual DbSet<ques_materialidade> ques_materialidade { get; set; }
        public virtual DbSet<ques_tentativa> ques_tentativa { get; set; }
        public virtual DbSet<reu> reu { get; set; }
        public virtual DbSet<sentenca> sentenca { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<vitima> vitima { get; set; }
        public virtual DbSet<vgerarcertificado> vgerarcertificado { get; set; }
        public virtual DbSet<vhistoricojuri> vhistoricojuri { get; set; }
        public virtual DbSet<vlistadepresenca> vlistadepresenca { get; set; }
        public virtual DbSet<vsorteiofuncoes> vsorteiofuncoes { get; set; }
    }
}
