//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisjuri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class faculdade
    {
        public faculdade()
        {
            this.curso = new HashSet<curso>();
            this.npj = new HashSet<npj>();
            this.usuario = new HashSet<usuario>();
        }
    
        public int id_faculdade { get; set; }
        public string nome_faculdade { get; set; }
        public string telefone_faculdade { get; set; }
        public string cnpj_faculdade { get; set; }
        public string endereco_faculdade { get; set; }
    
        public virtual ICollection<curso> curso { get; set; }
        public virtual ICollection<npj> npj { get; set; }
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
