//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisjuri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class juri
    {
        public juri()
        {
            this.documento = new HashSet<documento>();
            this.foto = new HashSet<foto>();
            this.inscricao = new HashSet<inscricao>();
            this.presenca = new HashSet<presenca>();
            this.processo = new HashSet<processo>();
        }
    
        public int id_juri { get; set; }
        public string nome_juri { get; set; }
        public System.DateTime data_hora_juri { get; set; }
        public string local_juri { get; set; }
        public bool juri_ativo { get; set; }
        public bool juri_sorteado { get; set; }
        public int fk_id_npj { get; set; }
    
        public virtual ICollection<documento> documento { get; set; }
        public virtual ICollection<foto> foto { get; set; }
        public virtual ICollection<inscricao> inscricao { get; set; }
        public virtual ICollection<presenca> presenca { get; set; }
        public virtual npj npj { get; set; }
        public virtual ICollection<processo> processo { get; set; }
    }
}
