//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisjuri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class npj
    {
        public npj()
        {
            this.juri = new HashSet<juri>();
        }
    
        public int id_npj { get; set; }
        public string nome_npj { get; set; }
        public string telefone_npj { get; set; }
        public string cnpj_npj { get; set; }
        public string endereco_npj { get; set; }
        public int fk_id_faculdade { get; set; }
    
        public virtual faculdade faculdade { get; set; }
        public virtual ICollection<juri> juri { get; set; }
    }
}
