//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisjuri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil
    {
        public perfil()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public int id_perfil { get; set; }
        public string nome_perfil { get; set; }
        public string descricao_perfil { get; set; }
    
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
