//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisjuri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class presenca
    {
        public int id_presenca { get; set; }
        public int pfk_id_juri { get; set; }
        public int pfk_id_inscricao { get; set; }
        public bool pres_entrada { get; set; }
        public bool conselho_sentenca { get; set; }
        public bool pres_saida_total { get; set; }
        public bool pres_saida_parcial { get; set; }
        public Nullable<System.TimeSpan> hora_saida_parcial { get; set; }
        public string horas_certif { get; set; }
    
        public virtual inscricao inscricao { get; set; }
        public virtual juri juri { get; set; }
    }
}
