//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisjuri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.inscricao = new HashSet<inscricao>();
        }
    
        public int id_usuario { get; set; }
        public string nome_completo { get; set; }
        public string cpf_usuario { get; set; }
        public string senha_usuario { get; set; }
        public string email_usuario { get; set; }
        public string num_matric_aluno { get; set; }
        public Nullable<int> periodo_aluno { get; set; }
        public string telefone_usuario { get; set; }
        public int fk_id_perfil { get; set; }
        public int fk_id_faculdade { get; set; }
        public Nullable<int> fk_id_curso { get; set; }
    
        public virtual curso curso { get; set; }
        public virtual faculdade faculdade { get; set; }
        public virtual ICollection<inscricao> inscricao { get; set; }
        public virtual perfil perfil { get; set; }
    }
}
